CXX = g++

CPPFLAGS = -I. -I../include
CXXFLAGS = -g
LDFLAGS = $(shell pkg-config --libs glew) -lglut

SOURCES = "$(wildcard *.cpp) ../common/util.cpp"
OBJECTS = $(SOURCES:.cpp=.o)
TARGET = main.exe


debug:
	@echo $(SOURCES)
